trigger: none

variables:
  NOTEBOOK_WORKING_DIR: $(System.DefaultWorkingDirectory)

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: 'validate_notebooks'
  displayName: 'Validate Databricks Notebooks'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: 3.9.5
        addToPath: true
        architecture: 'x64'
      displayName: 'Use Python Version: 3.9.5'